version: "3.9"
services:
  db:
    image: postgres:15
    container_name: hw_defect_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hw_defects
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hw_defects"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
